using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using PECB.SupportDesk.Api.Contracts; using PECB.SupportDesk.Api.Data; using PECB.SupportDesk.Api.Models; using PECB.SupportDesk.Api.Services;
namespace PECB.SupportDesk.Api.Controllers;
[ApiController,Route("api/tickets")]
public sealed class TicketsController(SupportDeskDbContext db,ITicketWorkflowService workflow):ControllerBase {
 [HttpGet] public async Task<PagedResult<TicketListDto>> List([FromQuery]string? search,[FromQuery]TicketStatus? status,[FromQuery]TicketPriority? priority,[FromQuery]int? agentId,[FromQuery]bool overdueOnly=false,[FromQuery]int page=1,[FromQuery]int pageSize=10,[FromQuery]string sortBy="createdDate",[FromQuery]string sortDirection="desc"){page=Math.Max(1,page);pageSize=new[]{10,50,200}.Contains(pageSize)?pageSize:10;var q=db.Tickets.AsNoTracking().Include(x=>x.AssignedAgent).AsQueryable();if(!string.IsNullOrWhiteSpace(search)){search=search.Trim();q=q.Where(x=>x.Reference.Contains(search)||x.Title.Contains(search)||x.CustomerName.Contains(search));}if(status.HasValue)q=q.Where(x=>x.Status==status);if(priority.HasValue)q=q.Where(x=>x.Priority==priority);if(agentId.HasValue)q=q.Where(x=>x.AssignedAgentId==agentId);var now=DateTimeOffset.UtcNow;if(overdueOnly)q=q.Where(x=>x.DueDate<now&&x.Status!=TicketStatus.Resolved&&x.Status!=TicketStatus.Closed);var desc=sortDirection.Equals("desc",StringComparison.OrdinalIgnoreCase);q=(sortBy.ToLowerInvariant(),desc) switch{("reference",false)=>q.OrderBy(x=>x.Reference),("reference",true)=>q.OrderByDescending(x=>x.Reference),("title",false)=>q.OrderBy(x=>x.Title),("title",true)=>q.OrderByDescending(x=>x.Title),("customer",false)=>q.OrderBy(x=>x.CustomerName),("customer",true)=>q.OrderByDescending(x=>x.CustomerName),("priority",false)=>q.OrderBy(x=>x.Priority),("priority",true)=>q.OrderByDescending(x=>x.Priority),("status",false)=>q.OrderBy(x=>x.Status),("status",true)=>q.OrderByDescending(x=>x.Status),("agent",false)=>q.OrderBy(x=>x.AssignedAgent==null?"":x.AssignedAgent.FullName),("agent",true)=>q.OrderByDescending(x=>x.AssignedAgent==null?"":x.AssignedAgent.FullName),("duedate",false)=>q.OrderBy(x=>x.DueDate),("duedate",true)=>q.OrderByDescending(x=>x.DueDate),("createddate",false)=>q.OrderBy(x=>x.CreatedDate),_=>q.OrderByDescending(x=>x.CreatedDate)};var total=await q.CountAsync();var rows=await q.Skip((page-1)*pageSize).Take(pageSize).ToListAsync();return new(rows.Select(x=>MapList(x,now)).ToArray(),page,pageSize,total,(int)Math.Ceiling(total/(double)pageSize));}
 [HttpGet("{id:int}")] public async Task<ActionResult<TicketDetailDto>> Get(int id){var t=await Load(id);return t is null?NotFound():MapDetail(t);}
 [HttpPost] public async Task<ActionResult<TicketDetailDto>> Create(CreateTicketRequest r){var now=DateTimeOffset.UtcNow;var next=(await db.Tickets.MaxAsync(x=>(int?)x.Id)??0)+1;var t=new Ticket{Reference=$"TCK-{now.Year}-{next:0000}",Title=r.Title.Trim(),Description=r.Description.Trim(),CustomerName=r.CustomerName.Trim(),CustomerEmail=r.CustomerEmail.Trim(),Priority=r.Priority,Status=TicketStatus.New,CreatedDate=now,LastModifiedDate=now,DueDate=workflow.CalculateDueDate(now,r.Priority)};db.Tickets.Add(t);await db.SaveChangesAsync();return CreatedAtAction(nameof(Get),new{id=t.Id},MapDetail(t));}
 [HttpPut("{id:int}")] public async Task<ActionResult<TicketDetailDto>> Update(int id,UpdateTicketRequest r){var t=await Load(id);if(t is null)return NotFound();TicketWorkflowService.EnsureEditable(t);t.Title=r.Title.Trim();t.Description=r.Description.Trim();t.CustomerName=r.CustomerName.Trim();t.CustomerEmail=r.CustomerEmail.Trim();if(t.Priority!=r.Priority){t.Priority=r.Priority;t.DueDate=workflow.CalculateDueDate(t.CreatedDate,r.Priority);}t.LastModifiedDate=DateTimeOffset.UtcNow;await db.SaveChangesAsync();return MapDetail(t);}
 [HttpDelete("{id:int}")] public async Task<IActionResult> Delete(int id){var t=await db.Tickets.FindAsync(id);if(t is null)return NotFound();TicketWorkflowService.EnsureEditable(t);db.Remove(t);await db.SaveChangesAsync();return NoContent();}
 [HttpPut("{id:int}/assignment")] public async Task<ActionResult<TicketDetailDto>> Assign(int id,AssignAgentRequest r){var t=await Load(id);if(t is null)return NotFound();TicketWorkflowService.EnsureEditable(t);if(r.AgentId is null){t.AssignedAgent=null;t.AssignedAgentId=null;}else{var a=await db.Agents.FindAsync(r.AgentId);if(a is null)return NotFound(new ProblemDetails{Title="agent_not_found",Detail="The selected agent does not exist."});if(!a.Active)throw new TicketWorkflowException("inactive_agent","Inactive agents cannot be assigned to tickets.");t.AssignedAgent=a;t.AssignedAgentId=a.Id;}t.LastModifiedDate=DateTimeOffset.UtcNow;await db.SaveChangesAsync();return MapDetail(t);}
 [HttpPut("{id:int}/status")] public async Task<ActionResult<TicketDetailDto>> Status(int id,ChangeStatusRequest r){var t=await Load(id);if(t is null)return NotFound();workflow.ChangeStatus(t,r.Status,DateTimeOffset.UtcNow);await db.SaveChangesAsync();return MapDetail(t);}
 [HttpPost("{id:int}/comments")] public async Task<ActionResult<CommentDto>> Comment(int id,AddCommentRequest r){var t=await db.Tickets.FindAsync(id);if(t is null)return NotFound();TicketWorkflowService.EnsureEditable(t);var c=new TicketComment{TicketId=id,AuthorName=r.AuthorName.Trim(),Body=r.Body.Trim(),CreatedDate=DateTimeOffset.UtcNow};db.Comments.Add(c);t.LastModifiedDate=c.CreatedDate;await db.SaveChangesAsync();return Ok(new CommentDto(c.Id,c.AuthorName,c.Body,c.CreatedDate));}
 private Task<Ticket?> Load(int id)=>db.Tickets.Include(x=>x.AssignedAgent).Include(x=>x.Comments).FirstOrDefaultAsync(x=>x.Id==id);
 private static AgentDto? AgentMap(Agent? a)=>a is null?null:new(a.Id,a.FullName,a.Email,a.Department,a.Active);
 private static bool Overdue(Ticket t,DateTimeOffset now)=>t.DueDate<now&&t.Status is not TicketStatus.Resolved and not TicketStatus.Closed;
 private static TicketListDto MapList(Ticket t,DateTimeOffset now)=>new(t.Id,t.Reference,t.Title,t.CustomerName,t.Priority,t.Status,AgentMap(t.AssignedAgent),t.DueDate,t.CreatedDate,Overdue(t,now));
 private static TicketDetailDto MapDetail(Ticket t)=>new(t.Id,t.Reference,t.Title,t.Description,t.CustomerName,t.CustomerEmail,t.Priority,t.Status,AgentMap(t.AssignedAgent),t.CreatedDate,t.LastModifiedDate,t.ResolvedDate,t.ClosedDate,t.DueDate,Overdue(t,DateTimeOffset.UtcNow),t.Comments.OrderBy(x=>x.CreatedDate).Select(x=>new CommentDto(x.Id,x.AuthorName,x.Body,x.CreatedDate)).ToArray());
}
