services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PecbDesk!2026Strong"
    ports:
      - "1433:1433"
    volumes:
      - supportdesk-data:/var/opt/mssql
volumes:
  supportdesk-data:
