// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PECB.SupportDesk.Api.Data;

#nullable disable

namespace PECB.SupportDesk.Api.Data.Migrations
{
    [DbContext(typeof(SupportDeskDbContext))]
    [Migration("20260902194955_AddEliraAgent")]
    partial class AddEliraAgent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PECB.SupportDesk.Api.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Department = "Technical",
                            Email = "arta@pecb.test",
                            FullName = "Arta Krasniqi"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Department = "Billing",
                            Email = "blerim@pecb.test",
                            FullName = "Blerim Hoxha"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Department = "General",
                            Email = "dua@pecb.test",
                            FullName = "Dua Gashi"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Department = "Technical",
                            Email = "luan@pecb.test",
                            FullName = "Luan Berisha"
                        },
                        new
                        {
                            Id = 5,
                            Active = false,
                            Department = "General",
                            Email = "mira@pecb.test",
                            FullName = "Mira Shala"
                        },
                        new
                        {
                            Id = -1,
                            Active = true,
                            Department = "Billing",
                            Email = "elira@pecb.test",
                            FullName = "Elira Dervishi"
                        });
                });

            modelBuilder.Entity("PECB.SupportDesk.Api.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedAgentId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ClosedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("ResolvedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer1@example.com",
                            CustomerName = "Customer 1",
                            Description = "Seeded ticket 1 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 24, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Critical",
                            Reference = "TCK-2026-0001",
                            Status = "New",
                            Title = "Sample support request 1"
                        },
                        new
                        {
                            Id = 2,
                            AssignedAgentId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 23, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer2@example.com",
                            CustomerName = "Customer 2",
                            Description = "Seeded ticket 2 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 23, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "High",
                            Reference = "TCK-2026-0002",
                            Status = "InProgress",
                            Title = "Sample support request 2"
                        },
                        new
                        {
                            Id = 3,
                            AssignedAgentId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer3@example.com",
                            CustomerName = "Customer 3",
                            Description = "Seeded ticket 3 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Normal",
                            Reference = "TCK-2026-0003",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Resolved",
                            Title = "Sample support request 3"
                        },
                        new
                        {
                            Id = 4,
                            AssignedAgentId = 1,
                            ClosedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer4@example.com",
                            CustomerName = "Customer 4",
                            Description = "Seeded ticket 4 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Low",
                            Reference = "TCK-2026-0004",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Closed",
                            Title = "Sample support request 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer5@example.com",
                            CustomerName = "Customer 5",
                            Description = "Seeded ticket 5 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 20, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Critical",
                            Reference = "TCK-2026-0005",
                            Status = "New",
                            Title = "Sample support request 5"
                        },
                        new
                        {
                            Id = 6,
                            AssignedAgentId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 19, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer6@example.com",
                            CustomerName = "Customer 6",
                            Description = "Seeded ticket 6 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 19, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "High",
                            Reference = "TCK-2026-0006",
                            Status = "InProgress",
                            Title = "Sample support request 6"
                        },
                        new
                        {
                            Id = 7,
                            AssignedAgentId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer7@example.com",
                            CustomerName = "Customer 7",
                            Description = "Seeded ticket 7 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Normal",
                            Reference = "TCK-2026-0007",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Resolved",
                            Title = "Sample support request 7"
                        },
                        new
                        {
                            Id = 8,
                            AssignedAgentId = 1,
                            ClosedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer8@example.com",
                            CustomerName = "Customer 8",
                            Description = "Seeded ticket 8 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Low",
                            Reference = "TCK-2026-0008",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Closed",
                            Title = "Sample support request 8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer9@example.com",
                            CustomerName = "Customer 9",
                            Description = "Seeded ticket 9 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 24, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Critical",
                            Reference = "TCK-2026-0009",
                            Status = "New",
                            Title = "Sample support request 9"
                        },
                        new
                        {
                            Id = 10,
                            AssignedAgentId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 23, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer10@example.com",
                            CustomerName = "Customer 10",
                            Description = "Seeded ticket 10 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 23, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "High",
                            Reference = "TCK-2026-0010",
                            Status = "InProgress",
                            Title = "Sample support request 10"
                        },
                        new
                        {
                            Id = 11,
                            AssignedAgentId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer11@example.com",
                            CustomerName = "Customer 11",
                            Description = "Seeded ticket 11 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Normal",
                            Reference = "TCK-2026-0011",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Resolved",
                            Title = "Sample support request 11"
                        },
                        new
                        {
                            Id = 12,
                            AssignedAgentId = 1,
                            ClosedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer12@example.com",
                            CustomerName = "Customer 12",
                            Description = "Seeded ticket 12 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Low",
                            Reference = "TCK-2026-0012",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Closed",
                            Title = "Sample support request 12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer13@example.com",
                            CustomerName = "Customer 13",
                            Description = "Seeded ticket 13 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 20, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Critical",
                            Reference = "TCK-2026-0013",
                            Status = "New",
                            Title = "Sample support request 13"
                        },
                        new
                        {
                            Id = 14,
                            AssignedAgentId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 19, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer14@example.com",
                            CustomerName = "Customer 14",
                            Description = "Seeded ticket 14 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 19, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "High",
                            Reference = "TCK-2026-0014",
                            Status = "InProgress",
                            Title = "Sample support request 14"
                        },
                        new
                        {
                            Id = 15,
                            AssignedAgentId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer15@example.com",
                            CustomerName = "Customer 15",
                            Description = "Seeded ticket 15 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Normal",
                            Reference = "TCK-2026-0015",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Resolved",
                            Title = "Sample support request 15"
                        },
                        new
                        {
                            Id = 16,
                            AssignedAgentId = 1,
                            ClosedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer16@example.com",
                            CustomerName = "Customer 16",
                            Description = "Seeded ticket 16 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Low",
                            Reference = "TCK-2026-0016",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Closed",
                            Title = "Sample support request 16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer17@example.com",
                            CustomerName = "Customer 17",
                            Description = "Seeded ticket 17 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 24, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Critical",
                            Reference = "TCK-2026-0017",
                            Status = "New",
                            Title = "Sample support request 17"
                        },
                        new
                        {
                            Id = 18,
                            AssignedAgentId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 23, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer18@example.com",
                            CustomerName = "Customer 18",
                            Description = "Seeded ticket 18 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 23, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "High",
                            Reference = "TCK-2026-0018",
                            Status = "InProgress",
                            Title = "Sample support request 18"
                        },
                        new
                        {
                            Id = 19,
                            AssignedAgentId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer19@example.com",
                            CustomerName = "Customer 19",
                            Description = "Seeded ticket 19 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Normal",
                            Reference = "TCK-2026-0019",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Resolved",
                            Title = "Sample support request 19"
                        },
                        new
                        {
                            Id = 20,
                            AssignedAgentId = 1,
                            ClosedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer20@example.com",
                            CustomerName = "Customer 20",
                            Description = "Seeded ticket 20 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Low",
                            Reference = "TCK-2026-0020",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Closed",
                            Title = "Sample support request 20"
                        },
                        new
                        {
                            Id = -20,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer21@example.com",
                            CustomerName = "Customer 21",
                            Description = "Seeded ticket 21 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 20, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Critical",
                            Reference = "TCK-SEED-0021",
                            Status = "New",
                            Title = "Sample support request 21"
                        },
                        new
                        {
                            Id = -19,
                            AssignedAgentId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 19, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer22@example.com",
                            CustomerName = "Customer 22",
                            Description = "Seeded ticket 22 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 19, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "High",
                            Reference = "TCK-SEED-0022",
                            Status = "InProgress",
                            Title = "Sample support request 22"
                        },
                        new
                        {
                            Id = -18,
                            AssignedAgentId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer23@example.com",
                            CustomerName = "Customer 23",
                            Description = "Seeded ticket 23 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Normal",
                            Reference = "TCK-SEED-0023",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Resolved",
                            Title = "Sample support request 23"
                        },
                        new
                        {
                            Id = -17,
                            AssignedAgentId = 1,
                            ClosedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer24@example.com",
                            CustomerName = "Customer 24",
                            Description = "Seeded ticket 24 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Low",
                            Reference = "TCK-SEED-0024",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Closed",
                            Title = "Sample support request 24"
                        },
                        new
                        {
                            Id = -16,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer25@example.com",
                            CustomerName = "Customer 25",
                            Description = "Seeded ticket 25 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 24, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Critical",
                            Reference = "TCK-SEED-0025",
                            Status = "New",
                            Title = "Sample support request 25"
                        },
                        new
                        {
                            Id = -15,
                            AssignedAgentId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 23, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer26@example.com",
                            CustomerName = "Customer 26",
                            Description = "Seeded ticket 26 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 23, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "High",
                            Reference = "TCK-SEED-0026",
                            Status = "InProgress",
                            Title = "Sample support request 26"
                        },
                        new
                        {
                            Id = -14,
                            AssignedAgentId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer27@example.com",
                            CustomerName = "Customer 27",
                            Description = "Seeded ticket 27 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Normal",
                            Reference = "TCK-SEED-0027",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Resolved",
                            Title = "Sample support request 27"
                        },
                        new
                        {
                            Id = -13,
                            AssignedAgentId = 1,
                            ClosedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer28@example.com",
                            CustomerName = "Customer 28",
                            Description = "Seeded ticket 28 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Low",
                            Reference = "TCK-SEED-0028",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Closed",
                            Title = "Sample support request 28"
                        },
                        new
                        {
                            Id = -12,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer29@example.com",
                            CustomerName = "Customer 29",
                            Description = "Seeded ticket 29 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 20, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Critical",
                            Reference = "TCK-SEED-0029",
                            Status = "New",
                            Title = "Sample support request 29"
                        },
                        new
                        {
                            Id = -11,
                            AssignedAgentId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 19, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer30@example.com",
                            CustomerName = "Customer 30",
                            Description = "Seeded ticket 30 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 19, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "High",
                            Reference = "TCK-SEED-0030",
                            Status = "InProgress",
                            Title = "Sample support request 30"
                        },
                        new
                        {
                            Id = -10,
                            AssignedAgentId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer31@example.com",
                            CustomerName = "Customer 31",
                            Description = "Seeded ticket 31 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Normal",
                            Reference = "TCK-SEED-0031",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Resolved",
                            Title = "Sample support request 31"
                        },
                        new
                        {
                            Id = -9,
                            AssignedAgentId = 1,
                            ClosedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer32@example.com",
                            CustomerName = "Customer 32",
                            Description = "Seeded ticket 32 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Low",
                            Reference = "TCK-SEED-0032",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Closed",
                            Title = "Sample support request 32"
                        },
                        new
                        {
                            Id = -8,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer33@example.com",
                            CustomerName = "Customer 33",
                            Description = "Seeded ticket 33 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 24, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Critical",
                            Reference = "TCK-SEED-0033",
                            Status = "New",
                            Title = "Sample support request 33"
                        },
                        new
                        {
                            Id = -7,
                            AssignedAgentId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 23, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer34@example.com",
                            CustomerName = "Customer 34",
                            Description = "Seeded ticket 34 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 23, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "High",
                            Reference = "TCK-SEED-0034",
                            Status = "InProgress",
                            Title = "Sample support request 34"
                        },
                        new
                        {
                            Id = -6,
                            AssignedAgentId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer35@example.com",
                            CustomerName = "Customer 35",
                            Description = "Seeded ticket 35 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Normal",
                            Reference = "TCK-SEED-0035",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 22, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Resolved",
                            Title = "Sample support request 35"
                        },
                        new
                        {
                            Id = -5,
                            AssignedAgentId = 1,
                            ClosedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer36@example.com",
                            CustomerName = "Customer 36",
                            Description = "Seeded ticket 36 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Low",
                            Reference = "TCK-SEED-0036",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 21, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Closed",
                            Title = "Sample support request 36"
                        },
                        new
                        {
                            Id = -4,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer37@example.com",
                            CustomerName = "Customer 37",
                            Description = "Seeded ticket 37 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 20, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Critical",
                            Reference = "TCK-SEED-0037",
                            Status = "New",
                            Title = "Sample support request 37"
                        },
                        new
                        {
                            Id = -3,
                            AssignedAgentId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 19, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer38@example.com",
                            CustomerName = "Customer 38",
                            Description = "Seeded ticket 38 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 19, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "High",
                            Reference = "TCK-SEED-0038",
                            Status = "InProgress",
                            Title = "Sample support request 38"
                        },
                        new
                        {
                            Id = -2,
                            AssignedAgentId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer39@example.com",
                            CustomerName = "Customer 39",
                            Description = "Seeded ticket 39 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Normal",
                            Reference = "TCK-SEED-0039",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 18, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Resolved",
                            Title = "Sample support request 39"
                        },
                        new
                        {
                            Id = -1,
                            AssignedAgentId = 1,
                            ClosedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "customer40@example.com",
                            CustomerName = "Customer 40",
                            Description = "Seeded ticket 40 for evaluating the workflow.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Low",
                            Reference = "TCK-SEED-0040",
                            ResolvedDate = new DateTimeOffset(new DateTime(2026, 8, 25, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Closed",
                            Title = "Sample support request 40"
                        });
                });

            modelBuilder.Entity("PECB.SupportDesk.Api.Models.TicketComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PECB.SupportDesk.Api.Models.Ticket", b =>
                {
                    b.HasOne("PECB.SupportDesk.Api.Models.Agent", "AssignedAgent")
                        .WithMany("Tickets")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedAgent");
                });

            modelBuilder.Entity("PECB.SupportDesk.Api.Models.TicketComment", b =>
                {
                    b.HasOne("PECB.SupportDesk.Api.Models.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("PECB.SupportDesk.Api.Models.Agent", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("PECB.SupportDesk.Api.Models.Ticket", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
